In [1]:
print(2+3)

5


In [2]:
# Print the series data with index.
import numpy as np
series=np.array([1,20,30,4,5])
print(series[2])

30


In [3]:
# If two initialization is same then last is considered as result
import numpy as np
arr=np.array([1,2,3,4,5])
arr=np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


In [4]:
# Insert the value in the last of an array.
import numpy as np
arr=np.array([1,2,3,4,5])
arr=np.append(arr,60)
print(arr)

[ 1  2  3  4  5 60]


In [5]:
# Basic Arithmetic Operation.    a. Add two array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
a+b

array([3, 5, 7, 9, 6])

In [6]:
# b. Substract two array using 1-D Array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
# a-b
np.add(a,b)

array([3, 5, 7, 9, 6])

In [7]:
# c. Multiplication two array using 1-D Array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
# a*b
np.multiply(a,b)

array([ 2,  6, 12, 20,  5])

In [8]:
# d. Division two array using 1-D Array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
# a/b
np.divide(a,b)

array([0.5       , 0.66666667, 0.75      , 0.8       , 5.        ])

In [9]:
# Division two array using 2-D Array
import numpy as np
a=np.array([[1,2,0],[2,3,5]])
b=np.array([[2,3,4],[2,3,1]])
# a/b
np.divide(a,b)

array([[0.5       , 0.66666667, 0.        ],
       [1.        , 1.        , 5.        ]])

In [10]:
# add two array using 2-D Array
import numpy as np
a=np.array([[1,2,0],[2,3,5]])
b=np.array([[2,3,4],[2,3,1]])
# a+b
print(a+b)

[[3 5 4]
 [4 6 6]]


In [11]:
# Universal Function :-      a. Square root of a number
a=np.array([[1,2,0],[2,3,5]])
np.sqrt(a)

array([[1.        , 1.41421356, 0.        ],
       [1.41421356, 1.73205081, 2.23606798]])

In [12]:
# b. Cube root of a number
a=np.array([[1,2,0],[2,3,5]])
cube=a**3
print(cube)
 

[[  1   8   0]
 [  8  27 125]]


In [13]:
# c.Greater than 
a=np.array([1,2,4 ])
b=np.array([0,7,3])
np.greater(a,b)

array([ True, False,  True])

In [14]:
# d. Less than 
import numpy as np
a=np.array([[1,2,4],[2,4,6]])
b=np.array([[0,7,3],[1,3,5]])
np.less(a,b)

array([[False,  True, False],
       [False, False, False]])

In [15]:
# e. Equal to
import numpy as np
a=np.array([[1,2,4],[2,4,6]])
b=np.array([[0,7,3],[2,4,6]])
np.equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [16]:
# 3. Aggregration Functions:- Its are used to combine multiple values into a single value. They are used in conjunction with.      a. mean find 
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
m=b2.mean(arr)
m

np.float64(12.5)

In [17]:

import numpy as b2 
a=b2.array([3,4,6])
b2.mean(a)
 


np.float64(4.333333333333333)

In [18]:
# b. Square of a number.
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
b2.square(a)



array([[ 1,  4, 16],
       [ 4, 16, 36]])

In [19]:
# c. Min of number
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
b2.min(a)


np.int64(1)

In [20]:
# d. Max of number
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
b2.max(a)

np.int64(6)

In [21]:
# 4. Matrix Multiplication.   a.multiply applicable for 1-D array
import numpy as b2 
a=b2.array([1,2,4 ])
b=b2.array([1,2,3])
b2.dot(a,b)


np.int64(17)

In [22]:
# Method-2
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,3,2,1,7])
a@b

np.int64(55)

In [23]:
# b. Reshape:- Used to convert the matrix 2*3 into 3*2.
 
import numpy as np
a=np.array([[1,4,5],[2,3,6]])
np.reshape(a,(3,2))



array([[1, 4],
       [5, 2],
       [3, 6]])

In [24]:
# c. Transpose:- Used to convert the matrix 2*3 into 3*2.
import numpy as np
a=np.array([[1,4,5],[2,3,6]])
a.T
 

array([[1, 2],
       [4, 3],
       [5, 6]])

In [25]:
# d. Determinant:- Used to find the determinant of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
np.linalg.det(a)

 

np.float64(49.99999999999999)

In [26]:
# e. Diagonal:- Used to find the diagonal elements of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
np.diagonal(a)
 

array([1, 3, 9])

In [27]:
# f. DiagProd:- Used to find the product of diagonal elements of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
ans=np.diagonal(a)
np.prod(ans)
 
 

np.int64(27)

In [28]:
# g. DiagSum:- Used to find the sum of diagonal elements of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
ans=np.diagonal(a)
np.sum(ans)
 

np.int64(13)

In [29]:

# h. Flatten:- Used to convert the matrix 2*3 into 1*6 
a=np.array([[1,4,5],[2,3,6]])
a.flatten()

array([1, 4, 5, 2, 3, 6])

In [30]:

# i. Inverse:- Used to find the inverse of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6]])
np.invert(a)

 

array([[-2, -5, -6],
       [-3, -4, -7]])