In [2]:
print(2+3)

5


In [3]:
import numpy as np

arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:

s=np.sqrt(arr)
m=np.mean(arr)
print(s)
m


[1.         1.41421356 1.73205081 2.         2.23606798]


3.0

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,3,2,1,7])
a@b

55

In [3]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)


[10 20 30 40 50]


In [1]:
import numpy as np
series=np.array([1,2,3,4,5])
print(series[2])

3
