In [1]:
print(2+3)

5


In [ ]:
# Print the series data with index.
import numpy as np
series=np.array([1,20,30,4,5])
print(series[2])

In [ ]:
# If two initialization is same then last is considered as result
import numpy as np
arr=np.array([1,2,3,4,5])
arr=np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


In [ ]:
# Insert the value in the last of an array.
import numpy as np
arr=np.array([1,2,3,4,5])
arr=np.append(arr,60)
print(arr)

[ 1  2  3  4  5 60]


In [ ]:
# Basic Arithmetic Operation.    a. Add two array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
a+b

array([3, 5, 7, 9, 6])

In [ ]:
# b. Substract two array using 1-D Array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
# a-b
np.add(a,b)

array([3, 5, 7, 9, 6])

In [ ]:
# c. Multiplication two array using 1-D Array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
# a*b
np.multiply(a,b)

array([ 2,  6, 12, 20,  5])

In [ ]:
# d. Division two array using 1-D Array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,1])
# a/b
np.divide(a,b)

array([0.5       , 0.66666667, 0.75      , 0.8       , 5.        ])

In [17]:
# Division two array using 2-D Array
import numpy as np
a=np.array([[1,2,0],[2,3,5]])
b=np.array([[2,3,4],[2,3,1]])
# a/b
np.divide(a,b)

array([[0.5       , 0.66666667, 0.        ],
       [1.        , 1.        , 5.        ]])

In [18]:
# add two array using 2-D Array
import numpy as np
a=np.array([[1,2,0],[2,3,5]])
b=np.array([[2,3,4],[2,3,1]])
# a+b
print(a+b)

[[3 5 4]
 [4 6 6]]


In [ ]:
# Universal Function :-      a. Square root of a number
a=np.array([[1,2,0],[2,3,5]])
np.sqrt(a)

array([[1.        , 1.41421356, 0.        ],
       [1.41421356, 1.73205081, 2.23606798]])

In [ ]:
# b. Cube root of a number
a=np.array([[1,2,0],[2,3,5]])
cube=a**3
print(cube)
 

[[  1   8   0]
 [  8  27 125]]


In [24]:
# c.Greater than 
a=np.array([1,2,4 ])
b=np.array([0,7,3])
np.greater(a,b)

array([ True, False,  True])

In [ ]:
# d. Less than 
import numpy as np
a=np.array([[1,2,4],[2,4,6]])
b=np.array([[0,7,3],[1,3,5]])
np.less(a,b)

array([[False,  True, False],
       [False, False, False]])

In [ ]:
# e. Equal to
import numpy as np
a=np.array([[1,2,4],[2,4,6]])
b=np.array([[0,7,3],[2,4,6]])
np.equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [28]:
# 3. Aggregration Functions:- Its are used to combine multiple values into a single value. They are used in conjunction with.      a. mean find 
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
m=b2.mean(arr)
m

12.5

In [34]:

import numpy as b2 
a=b2.array([3,4,6])
b2.mean(a)
 


4.333333333333333

In [ ]:
# b. Square of a number.
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
b2.square(a)



array([[ 1,  4, 16],
       [ 4, 16, 36]])

In [38]:
# c. Min of number
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
b2.min(a)


1

In [39]:
# d. Max of number
import numpy as b2 
a=b2.array([[1,2,4],[2,4,6]])
b2.max(a)

6

In [ ]:
# 4. Matrix Multiplication.   a.multiply applicable for 1-D array
import numpy as b2 
a=b2.array([1,2,4 ])
b=b2.array([1,2,3])
b2.dot(a,b)


17

In [ ]:
# Method-2
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,3,2,1,7])
a@b

55

In [47]:
# b. Reshape:- Used to convert the matrix 2*3 into 3*2.
 
import numpy as np
a=np.array([[1,4,5],[2,3,6]])
np.reshape(a,(3,2))



array([[1, 4],
       [5, 2],
       [3, 6]])

In [ ]:
# c. Transpose:- Used to convert the matrix 2*3 into 3*2.
import numpy as np
a=np.array([[1,4,5],[2,3,6]])
a.T
 

array([[1, 2],
       [4, 3],
       [5, 6]])

In [53]:
# d. Determinant:- Used to find the determinant of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
np.linalg.det(a)

 

49.99999999999999

In [ ]:
# e. Diagonal:- Used to find the diagonal elements of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
np.diagonal(a)
 

In [ ]:
# f. DiagProd:- Used to find the product of diagonal elements of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
ans=np.diagonal(a)
np.prod(ans)
 
 

27

In [ ]:
# g. DiagSum:- Used to find the sum of diagonal elements of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6],[7,8,9]])
ans=np.diagonal(a)
np.sum(ans)
 

13

In [63]:

# h. Flatten:- Used to convert the matrix 2*3 into 1*6 
a=np.array([[1,4,5],[2,3,6]])
a.flatten()

array([1, 4, 5, 2, 3, 6])

In [ ]:

# i. Inverse:- Used to find the inverse of the matrix.
import numpy as np
a=np.array([[1,4,5],[2,3,6]])
np.invert(a)

 

array([[-2, -5, -6],
       [-3, -4, -7]])

In [71]:
 
#  Two types of Structure.  a. Series = column wise form & 1-waqy Dimentional.
#                           b. Data Frame = Tabular representation of 2-D or more.
# 1. Print the data through Series.       Note- capital S is used in Series
import pandas as pd
a=[10,20,30,40,50]
ans=pd.Series(a)
print(ans)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
# 2. Print the series data with index.
import pandas as pd
a=[1,2,3,4,5]
ans=pd.Series(a)
print(ans[2])

# import pandas as pd
# series=pd.array([1,2,3,4,5])
# print(series[2])

3


In [ ]:
# 3. Print the ywo column of calories and duration and insert the value.
import pandas as pd
data = {
  "calories": [40, 30, 10],
  "duration": [50, 20, 45]
} 
df = pd.DataFrame(data)

print(df)

   calories  duration
0        40        50
1        30        20
2        10        45


In [81]:
# 4. Create three column of name,age and city and insert the values with the index name person.
import pandas as pd
data = {
  "name": ['Ayu','B2',"Raj"],
  "age": [15, 20, 25],
  "city":['Abad',"Patna","Gaya"]
  
}  
df = pd.DataFrame(data, index=["person1", "person2", "person3"])
print(df)

        name  age   city
person1  Ayu   15   Abad
person2   B2   20  Patna
person3  Raj   25   Gaya


In [ ]:
# 5. Create a data form from a dictonary .
data = {
    1: {"Name": "Ayu", "Age": 25},
    2: {"Name": "B2", "Age": 20},
    3: {"Name": "Raj", "Age": 22}
}
for key, value in data.items():
    print(f"ID: {key}, Data: {value}")
 

ID: 1, Data: {'Name': 'Ayu', 'Age': 25}
ID: 2, Data: {'Name': 'B2', 'Age': 20}
ID: 3, Data: {'Name': 'Raj', 'Age': 22}


In [ ]:
# 6. Select the specific column name.
import pandas as pd
data = {
  "name": ['Ayu','B2',"Raj"],
  "age": [15, 20, 25],
  "city":['Abad',"Patna","Gaya"]
  
} 
df = pd.DataFrame(data)
df_selected = df[["name"]]
print(df_selected)

  name
0  Ayu
1   B2
2  Raj


In [ ]:
 # 7. Filter rows based on a condition is higher than 25.
import pandas as pd
data = {
  "name": ['Ayu','B2',"Raj"],
  "age": [35, 20, 25],
  "city":['Abad',"Patna","Gaya"]
  
} 
df = pd.DataFrame(data)
filtered_df = df[df["age"] > 25]
print(filtered_df)

  name  age  city
0  Ayu   35  Abad


In [ ]:
# 8. Add a new column of salary and insert the values.
import pandas as pd
data = {
    "name": ['Ayu', 'B2', 'Raj'],
    "age": [15, 20, 25],
    "city": ['Abad', 'Patna', 'Gaya']
}
df = pd.DataFrame(data) 
df["Salary"] = [50000, 60000, 45000]
print(df)

In [ ]:
# 9. calculate the mean of a numeric value.
import pandas as pd

data = {
    "name": ['Ayu', 'B2', 'Raj'],
    "age": [15, 20, 25],
    "city": ['Abad', 'Patna', 'Gaya'],
    "Salary": [50000, 60000, 45000]
}
df = pd.DataFrame(data) 
mean_values = df.mean(numeric_only=True)
print(mean_values)

age          20.000000
Salary    51666.666667
dtype: float64
